{exec} = require 'child_process'

phrase = "Have your cake and eat it!"

task 'say', "script will run this first command only.", ->
	exec "say #{phrase}"
	console.log phrase

task 'two', "script will ignore this task.", ->
	console.error "Task 2 ran but shouldn't have!"
