.PHONY: makefile test #do not reference files.

makefile: test #or highlight and run the following (excluding the initial "@").

	@set This bash command; echo $@ ran successfully.

test:
	@printf This" "
